### ISSUE TITLE
建议加上一份好的ReadMe

### ISSUE THREAD

**Issue by EdisonTalk** [fancunwei/CsharpFanDemo#1]
提一个suggestion：
1.加上一份好的ReadMe，说明哪部分source code有哪些内容最好（可能需要学学Markdown）。
2.加上你的具体博客链接，这也是你自媒体的一部分。

**Comment by fancunwei** [comment]
ok,下篇实践都补上，感谢建议。
我一直用markdown写博客的。常用语法都很熟。

**Comment by fancunwei** [comment]
> 提一个suggestion：
> 1.加上一份好的ReadMe，说明哪部分source code有哪些内容最好（可能需要学学Markdown）。
> 2.加上你的具体博客链接，这也是你自媒体的一部分。

已加上ReadMe
